# ==============================================================================
# S10_module_preservation.R — Split-Half WGCNA Module Preservation
#
# Validates WGCNA module stability at small sample sizes (n=16-18) using
# split-half modulePreservation() from Langfelder & Horvath (2011), with
# per-stratum stratified sampling, 20 random splits, and permuted baseline.
#
# Input:
#   Pipeline runs under RUN_DIR/GEO_<GSE>_<prefix>/data/ (vst_matrix.rds,
#   sample_info.rds) — generated by S04_run_pipeline_wrapper.R
#
# Output:
#   benchmark_results/S10_GSE236646.rds
#   benchmark_results/S10_GSE307424.rds
#   figures/Supp_S10_module_preservation.pdf
#
# Usage:
#   source("S_config.R")
#   source("S10_module_preservation.R")
# ==============================================================================

source("S_config.R")
suppressPackageStartupMessages({library(WGCNA); library(ggplot2)})
tryCatch({allowWGCNAThreads(2)}, error = function(e) {try(disableWGCNAThreads(), silent = TRUE)})

N_SPLITS <- 20

# ---- Core function ----

run_split_half_preservation <- function(vst, si, seed) {
  set.seed(seed)
  gene_mad <- apply(vst, 1, mad)
  cutoff <- sort(gene_mad, decreasing = TRUE)[round(nrow(vst) * 0.5)]
  genes_use <- names(gene_mad)[gene_mad >= cutoff]

  si$stratum <- paste(si$Treatment, si$Time, sep = "_")
  halfA_idx <- c()
  for (st in unique(si$stratum)) {
    st_idx <- which(si$stratum == st)
    n_st <- length(st_idx); n_A <- max(1, floor(n_st / 2))
    halfA_idx <- c(halfA_idx, sample(st_idx, n_A))
  }
  halfB_idx <- setdiff(seq_len(nrow(si)), halfA_idx)

  dA <- t(vst[genes_use, halfA_idx]); dB <- t(vst[genes_use, halfB_idx])
  nA <- nrow(dA); nB <- nrow(dB)

  get_power <- function(dE, n_samp) {
    sft <- pickSoftThreshold(dE, powerVector = 1:20, networkType = "signed hybrid", verbose = 0)
    r2 <- max(-sign(sft$fitIndices[,3]) * sft$fitIndices[,2], na.rm = TRUE)
    if (r2 >= 0.8) sft$fitIndices$Power[which.max(-sign(sft$fitIndices[,3]) * sft$fitIndices[,2])]
    else if (n_samp < 20) 9 else 8
  }
  pwA <- get_power(dA, nA); pwB <- get_power(dB, nB)

  run_wgcna <- function(dE, power) {
    adj <- adjacency(dE, power = power, type = "signed hybrid")
    TOM <- TOMsimilarity(adj)
    tree <- hclust(as.dist(1 - TOM), method = "average")
    mods <- cutreeDynamic(dendro = tree, distM = 1 - TOM, deepSplit = 2,
                          minClusterSize = 20, pamRespectsDendro = FALSE)
    labels2colors(mods)
  }
  colsA <- run_wgcna(dA, pwA); colsB <- run_wgcna(dB, pwB)

  multiExpr <- list(A = list(data = dA), B = list(data = dB))
  multiColor <- list(A = colsA, B = colsB)

  mp <- tryCatch({
    modulePreservation(multiExpr, multiColor, referenceNetworks = 1, testNetworks = 2,
                       nPermutations = 100, randomSeed = seed, quickCor = 0, verbose = 0)
  }, error = function(e) NULL)
  if (is.null(mp)) return(NULL)

  zsum <- mp$preservation$Z$ref.A$inColumnsAlsoPresentIn.B
  zsum_df <- data.frame(module = rownames(zsum), Zsummary = zsum$Zsummary.pres)
  zsum_df <- zsum_df[!is.na(zsum_df$Zsummary) & zsum_df$module != "gold", ]

  data.frame(seed = seed, nA = nA, nB = nB, pwA = pwA, pwB = pwB,
             n_modules_A = nrow(zsum_df),
             n_strong = sum(zsum_df$Zsummary > 10, na.rm = TRUE),
             n_moderate = sum(zsum_df$Zsummary > 2 & zsum_df$Zsummary <= 10, na.rm = TRUE),
             n_weak = sum(zsum_df$Zsummary <= 2, na.rm = TRUE),
             median_Z = median(zsum_df$Zsummary, na.rm = TRUE),
             mean_Z = mean(zsum_df$Zsummary, na.rm = TRUE))
}

# ---- Dataset registry ----

DATASETS <- list(
  GSE236646 = list(
    label = "GSE236646 (n=16)",
    data_dir = file.path(RUN_DIR, "GEO_GSE236646_NPC", "data")
  ),
  GSE307424 = list(
    label = "GSE307424 (n=18)",
    data_dir = file.path(RUN_DIR, "GEO_GSE307424_Lung", "data")
  )
)

# ---- Run preservation for one dataset ----

run_preservation_dataset <- function(ds_name, ds_info) {
  cat(sprintf("\n========== S10: %s ==========\n\n", ds_info$label))

  vst <- readRDS(file.path(ds_info$data_dir, "vst_matrix.rds"))
  si  <- readRDS(file.path(ds_info$data_dir, "sample_info.rds"))

  cat(sprintf("Running %d splits (sequential)...\n", N_SPLITS))
  t0 <- Sys.time()
  results <- list()
  for (i in seq_len(N_SPLITS)) {
    cat(sprintf("  Split %2d/%d: ", i, N_SPLITS))
    t1 <- Sys.time()
    res <- run_split_half_preservation(vst, si, seed = i * 100)
    t_elapsed <- round(as.numeric(difftime(Sys.time(), t1, units = "secs")), 0)
    if (!is.null(res)) {
      res$split_id <- i; results[[i]] <- res
      cat(sprintf("modules=%d median_Z=%.2f strong=%d moderate=%d weak=%d (%ds)\n",
                  res$n_modules_A, res$median_Z, res$n_strong, res$n_moderate, res$n_weak, t_elapsed))
    } else {
      cat(sprintf("FAILED (%ds)\n", t_elapsed))
    }
  }
  elapsed <- round(as.numeric(difftime(Sys.time(), t0, units = "mins")), 0)
  cat(sprintf("All %d splits completed in %d min\n", N_SPLITS, elapsed))

  df <- do.call(rbind, results)

  # Permuted baseline (5 runs)
  cat("\nPermuted baseline...\n")
  perm_results <- list()
  for (i in 1:5) {
    si_perm <- si
    for (tp in unique(si$Time)) {
      tp_idx <- which(si$Time == tp)
      si_perm$Treatment[tp_idx] <- sample(si$Treatment[tp_idx])
    }
    res <- run_split_half_preservation(vst, si_perm, seed = 999 + i)
    if (!is.null(res)) perm_results[[i]] <- res
  }
  df_perm <- do.call(rbind, perm_results)

  # Save
  out_file <- file.path(BENCH_DIR, paste0("S10_", ds_name, ".rds"))
  saveRDS(list(results = df, permuted = df_perm), out_file)

  cat(sprintf("\n=== %s DONE ===\n", ds_name))
  cat(sprintf("Median Zsummary: %.2f +/- %.2f\n", mean(df$median_Z), sd(df$median_Z)))
  cat(sprintf("Strong preservation: %.1f%%\n", 100*sum(df$n_strong)/sum(df$n_modules_A)))
  cat(sprintf("Permuted baseline Z: %.2f\n", mean(df_perm$median_Z)))

  return(list(results = df, permuted = df_perm, label = ds_info$label))
}

# ---- Merge and plot ----

merge_and_plot <- function(all_results) {
  cat("\n========== S10 Merge: Combined Figure ==========\n\n")

  df_plot <- data.frame()
  for (nm in names(all_results)) {
    r <- all_results[[nm]]
    r$results$dataset <- r$label
    r$results$type <- "Real"
    keep_cols <- c("dataset", "type", "median_Z")
    df_plot <- rbind(df_plot, r$results[, keep_cols])

    if (!is.null(r$permuted) && nrow(r$permuted) > 0) {
      r$permuted$dataset <- r$label
      r$permuted$type <- "Permuted"
      df_plot <- rbind(df_plot, r$permuted[, keep_cols])
    }
  }

  p <- ggplot(df_plot, aes(x = dataset, y = median_Z, fill = type)) +
    geom_boxplot(outlier.size = 1) +
    geom_hline(yintercept = 10, linetype = "dashed", color = "#E64B35") +
    geom_hline(yintercept = 2, linetype = "dotted", color = "#F39B7F") +
    annotate("text", x = 2.3, y = 10.5, label = "Z=10 (strong)", color = "#E64B35", size = 3) +
    annotate("text", x = 2.3, y = 2.5, label = "Z=2 (weak-moderate)", color = "#F39B7F", size = 3) +
    labs(title = "Module Preservation Across Random Split-Halves",
         subtitle = "20 splits per dataset | modulePreservation() [Langfelder & Horvath 2011]",
         y = "Median Zsummary per split", x = "", fill = "") +
    theme_classic(12)

  ggsave(file.path(FIG_DIR_METHODS, "Supp_S10_module_preservation.pdf"), p, width = 8, height = 5)
  ggsave(file.path(FIG_DIR_METHODS, "Supp_S10_module_preservation.png"), p, width = 8, height = 5, dpi = 300)
  cat("[SAVED] Supp_S10_module_preservation.pdf\n")
}

# ---- Main ----

all_results <- list()
for (ds_name in names(DATASETS)) {
  ds_info <- DATASETS[[ds_name]]
  if (!file.exists(file.path(ds_info$data_dir, "vst_matrix.rds"))) {
    cat(sprintf("Skipping %s: vst_matrix.rds not found at %s\n", ds_name, ds_info$data_dir))
    next
  }
  all_results[[ds_name]] <- run_preservation_dataset(ds_name, ds_info)
}

if (length(all_results) >= 2) {
  merge_and_plot(all_results)
}
cat("\n=== S10 module preservation complete ===\n")
